name: Release

on:
  workflow_dispatch:
  release:
    types: [created]

jobs:
  build:
    name: Build application
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: '17'
    - name: Build with Gradle
      run: ./gradlew assembleFDroidRelease bundleFDroidRelease
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: smartautoclicker-release
        path: smartautoclicker/build/outputs/
